# Generated by Django 3.0.7 on 2020-08-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='People',
        ),
    ]
